# Generated by Django 5.0 on 2026-01-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('flavor_text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('image_slug', models.CharField(default='work-in-progress', max_length=100)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
