# Generated by Django 5.0 on 2026-01-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_slug',
            field=models.CharField(blank=True, help_text='Slug from Gallery Video', max_length=100),
        ),
    ]
