# Generated by Django 5.0 on 2026-01-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_video_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video_slug',
        ),
    ]
