# Generated by Django 5.0 on 2026-01-05 05:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_alter_project_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dmo5atv6g/image/upload/v1767583908/WIP.png', max_length=255, verbose_name='image'),
        ),
    ]
