# Generated by Django 5.0 on 2026-01-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.CharField(max_length=200),
        ),
    ]
