# Generated by Django 5.0 on 2026-01-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='flavor_text',
        ),
    ]
