# Generated by Django 5.0 on 2026-01-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_description_project_flavor_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='flavor_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
