# Generated by Django 5.0 on 2026-01-07 06:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Your Name', max_length=100)),
                ('nav_bar_title', models.CharField(default='Your Name', max_length=100)),
                ('home_page_title', models.CharField(default='Blurb', max_length=200)),
                ('about_bio_full', models.TextField(default='This is your about me bio. Edit it in the admin panel.')),
                ('about_email', models.EmailField(default='Your@email.com', max_length=254)),
                ('about_linkedin', models.URLField(blank=True)),
                ('profile_picture_slug', models.CharField(blank=True, max_length=100)),
                ('wip_image_slug', models.CharField(blank=True, max_length=100)),
                ('light_bg_color', models.CharField(default='#ffffff', max_length=7)),
                ('light_text_color', models.CharField(default='#1f2937', max_length=7)),
                ('light_nav_bar_color', models.CharField(default='#ffffff', max_length=7)),
                ('light_accent_color', models.CharField(default='#e63946', max_length=7)),
                ('dark_bg_color', models.CharField(default='#121212', max_length=7)),
                ('dark_text_color', models.CharField(default='#f3f4f6', max_length=7)),
                ('dark_nav_bar_color', models.CharField(default='#121212', max_length=7)),
                ('dark_accent_color', models.CharField(default='#ff8c00', max_length=7)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
