# Generated by Django 5.0 on 2026-01-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='resume_filename',
            field=models.CharField(default='default_resume', help_text='Enter the filename (without .pdf) located in static/docs/', max_length=100),
        ),
    ]
