# Generated by Django 5.0 on 2026-01-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_galleryvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryvideo',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='galleryvideo',
            old_name='video',
            new_name='video_file',
        ),
        migrations.RemoveField(
            model_name='galleryvideo',
            name='name',
        ),
        migrations.AddField(
            model_name='galleryvideo',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
